### PR TITLE
added History of APL in 50 Functions examples 19-23

### PR DESCRIPTION
**Pull request by frasiyav**
They could definitely be improved, especially the functions for combinations and combination indexing, but they should still be useful examples for people to compare with the original APL.

### CODE REVIEW

**Comment by mlochbaum** [comment]
Wow, thank you! Very nice style as well. I'll go through them thoroughly tomorrow; for now the only things I see that I'd do differently are too trivial to mention. Awesome how `IndexFromPermutation` shows off Suffixes.

**Comment by mlochbaum** [comment]
I've been through them now but didn't change much. As you say I don't want to get too far from the APL sources. I did change `⊏⎉2‿1` from `Permutations` to `⊸⊏˘` since I always find two ranks hard to decipher. I would probably have written `=∨=⟜0` rather than `=∨0=⊣` in `Combinations`, but whether this is any clearer is very much a matter of opinion and I didn't change it.

I added `∾∘⊔` as another way to invert a permutation in the comments (actually it's the same as `⍋` on any list of natural numbers). This idea is used a few times in the runtime with the definition `PermInv ← 1¨⊸GroupOrd`.

If you've got any comments about how working with BQN has been so far, or even suggestions about the language, I'd love to hear them!

**Comment by frasiyav** [comment]
I'm relatively new to APL, so take my feedback accordingly, but I really like the direction BQN is heading, especially in regards to Lisp-style functional programming. I also find the symbol choices to be clearer and more readable.
The only real difficulty I had was the lack of the inner product operator, which forces you to contend more carefully with rank (not necessarily a bad thing!), and not being able to do case headers where you first apply a function, i.e something like `1=≢⍵:` (maybe this is possible, I just couldn't figure it out, so I went with `◶`).
The documentation was very helpful, and the BQN-Dyalog dictionary page in particular was invaluable for finding my footing.

Interestingly, I had recently played around with Lehmer codes (Rfd and Dfr in the permutation indexing functions) in Dyalog before I came across the History of APL in 50 Functions, and there is a faster solution for Rfd, at least in Dyalog where they have all the vector/SIMD optimizations: `{⍵-0 0⍉+⍀∘.<⍨⍵}` or ``{𝕩-0‿0⍉+`<⌜˜𝕩}``. But, like you said, it doesn't show off the extremely neat suffixes function.

I don't have any informed suggestions, but there are a couple of features I am curious about:
If you plan to implement Obverse; it would be very neat to be able to define `IndexFromPermutation` and `PermutationFromIndex` as inverses so you could do something like `(1⊸+)⌾PermutationIndex`. And whether there will be ways of easily manipulating functions in macro-like ways, other than using `⍕` and then manipulating them as character vectors.

**Comment by mlochbaum** [comment]
dzaima just implemented specified inverses using the header syntax: discussion starts [here](https://chat.stackexchange.com/transcript/message/55860071#55860071) and tests are [here](https://github.com/dzaima/BQN/blob/a6619d5c9ed31c886f43c61a1840c596be314559/test/headers#L95). I think the header method is a better fit for this functionality than J's Obverse conjunction, and it also allows setting the left-argument inverse with a `𝕊˜⁼` header, which is impossible in J. I've included inverses in the permutation and combination functions. You still can't do `(1⊸+)⌾PermutationIndex` without specifying a length; for that Under would have to remember the initial length, which would require an Under header besides the inverse.

Headers only do destructuring and not testing, so requiring something like `𝕨(=∨0=⊣)𝕩` is impossible. I'm not happy with this but I haven't come up with a sensible way to make them more flexible. Probably more promising would be some sort of syntax trick to rearrange the inputs of `◶` and other operators so they look more like control structures. I also don't have plans to add anything macro-like now, but it's somewhere in the back of my mind. [KAP](https://github.com/lokedhs/array) has a decent macro system.

I think an advanced implementation could be able to vectorize `⊢+´∘>¨¯1↓↓` in a reasonable way. Certainly it would want to virtualize Suffixes much of the time to save memory/cache (J's new virtual blocks would accomplish this). The trick of rectangularizing and then taking the diagonal is pretty cool though.

**Comment by mlochbaum** [comment]
[Returns](https://mlochbaum.github.io/BQN/doc/block.html#returns) would allow guard-like logic with somewhat reasonable syntax: `𝕊→∘doStuff⍟cond value`.

**Comment by frasiyav** [comment]
The header system seemed a bit weird and confusing at first, but the more I see it, the more I like it. Specified inverses via headers instead of a modifier is no great loss when recovering Obverse is as easy as `_obv_ ← {F‿G←𝔽‿𝔾 ⋄ {𝕊: 𝕨F𝕩; 𝕊⁼: 𝕨G𝕩}}`, and I see your point with the left-argument inverse about headers being generally better. I hadn't even considered the idea of specifying Under, but thinking about it now, that's probably pretty basic, as you'd need that for defining new structural Under procedures.

My question about macros may have been a bit premature, as I'm starting to realize how powerful first-class functions with modifiers and roles already are.
```
_Cond←{𝕨({C: (1≠≠)◶⟨⊑, 1⊸↓{(⊑𝕩)◶⟨C𝕨, 1⊑𝕩⟩}⊑⟩𝕩}𝕗){𝔽}𝕩}
c ← ⟨
      ⟨5=⊢, "Five"⟩  # Cases
      ⟨10=⊢, "Ten"⟩
      ⟨0>⊣, -⟩
      ÷              # Default 
    ⟩

¯1‿0‿2‿5‿7‿10 c _Cond¨ ¯1‿0‿2‿5‿7‿10 
```
But I am happy to know macros are something you've given thought to.

**Comment by mlochbaum** [comment]
Was going to mention your `_Cond` strategy in the problems document and found that there's really a lot to say. [Here's the result](https://mlochbaum.github.io/BQN/doc/control.html). I used a similar technique to define `Match` in the runtime `src/r.bqn`, but hadn't really thought about making it more systematic to more-or-less replace macros.

**Pull request merged**
