### PR TITLE
Implement character based version of Explain

### PR DESCRIPTION
**Pull request by Detegr**
There's some code duplication with `e.bqn` that I didn't know how to share it between the implementations. All the logic used is from `e.bqn`, the representation is drawn using box-drawing characters. I think this implementation could be useful in terminal based interpreters, such as CBQN.

### CODE REVIEW

**Comment by Detegr** [comment]
Now that I think of it, I'm not sure if it's correct to call it ASCII as it's using Unicode characters :smile: well, whatever.

**Comment by Detegr** [comment]
It only now occurred to me that this isn't ASCII as it's using Unicode characters. Fixed that.

**Comment by mlochbaum** [comment]
Thanks, seems to work. There's no specific reason to keep the calling style the same as in e.bqn, is there? I'm thinking I'd like it to import the compiler so it can be called easily as a user-level library. It could be made to stand alone if the system provided the compiler.

**Comment by Detegr** [comment]
No, there's no technical reason to keep the calling style. User-level library sounds like a good idea.

**Pull request merged**
