### PR TITLE
editors: Add support for Dvorak keyboard layout

### PR DESCRIPTION
**Pull request by xelxebar**
# Overview

Support Dvorak keyboards without scrambling the locations of BQN symbols. Unfortunately, this does destroy the nice mnemonics.

# Notes

The XKB `bqn` layout file should work as-is, since it maps from raw
keycodes. However, inputrc and XCompose translate keysyms, meaning that
non-QWERTY layouts will scramble the arrangement of BQN symbols.

# Comments

The support here is probably half-baked, since I only focused on my immediate personal needs. If the support seems useful, maybe we can flesh out the PR with Windows and MacOS definitions as needed.

### CODE REVIEW

**Comment by mlochbaum** [comment]
I've been going back and forth on whether it makes sense to put this in the main BQN repository (the other option is to make a separate repository for it, and link to that). My worry is that the clutter makes things a little less convenient and more confusing for the large majority of qwerty users. And while dvorak is the most common alternate layout, there are a lot of other contenders, and supporting them all would take a lot of files.

I also don't have a good sense for whether it's worth it to keep the positioning for `↑↓` at the cost of losing letter correspondence for `𝔽` (and so on). It might not make sense to have a single dvorak keyboard, particularly because some users might want it to be easy to switch back and forth with qwerty and others might not.

Really not sure about any of this. Any comments that might help me make sense of it?

**Comment by xelxebar** [comment]
You bring up good points. I, too, was somewhat hesitant to even submit this for similar reasons.

Losing the nice mnemonic correspondences is definitely a bummer. Though, providing dvorak versions at least gives those users a choice what to prioritize---position vs mnemonics. Personally, I prioritize the ability to collaborate and use other people's keyboards over mnemonics. For me the latter are only really useful for learning, while the former retain constant utility.

Clutter is definitely annoying. It's a one-time cost for *someone* either way: do you marginally inconvenience qwerty users or significantly inconvenience the margin? Though perhaps the former could be mitigated with a suitable directory organization strategy? One potentially reasonable position to take is to let demand drive the creation of layouts instead of pre-emptively creating a bunch. This would at least let you slowly monitor the actual effects of any clutter.

Of course, it's also reasonable to take a hard-line stance and only rubber stamp qwerty in this repo, while potentially linking to other repos in the readme.

**Comment by xelxebar** [comment]
Oh, it also occurred to me, having these dvorak layouts gives the same effective layout as using `setxkbmap -option grp:switch dvorak,bqn`.

**Comment by mlochbaum** [comment]
I was able to make a BQN script to generate the XCompose and inputrc files! [This link](https://dzaima.github.io/paste/#0bVNbTxNBFH7vrxhHobtSWkHxAi3IxTuoeEEUoU53p@3S2Ut3drFSa3widdGoUYMPmBqMSXnihRhexGRf/RfzC/wJnplCwMjDbr5z5pzvXOab6lPqB88QEivvEH7S13/6zMDZc@cvnOrNvTh28fiJroXuk5qe76mqsNByvbn56QeX7tx7eP/ardv1BuFmsVRerLCh5OjdictXrl6/MTmI8fPlmrFUcOxUOvNodnxm7OZUdngE4YS55Pqk8n@1uflD1eqNZCrtPSuWDJ9lchhnh28/vHxl/M7kSA9xaWiZ5cDhvaO3Lt2/NnH13s27@edD1cVKrWA/XVoenL5@Y3Zs6sHMI6iWmCKeKlX/8@XTpoje/l4H0BbROxFtNBJ5zvL7xx9/5uHoW1602iRVEK3NQSSdovlZ04hY@VCAD5L0uK2LaEf6oh2x8l40d0X0Df6Fji3PG4lE3nK8MPCNPfoEQrZCUGINQVNibVVL4iTk5MTaD6gpvkcp/BhLEmBsbQKNDP4MmTIbIUO8/GUqjnjrLOB4q1/5NS0Xb6tDmRu9hQbkrDrSDPF6V@t43@ti5ROMIl591Tth0og2xJsWdB@30RRSuzitiAdk5U1gb0iGC2qwD3pCjlUzXNtzOT2Yq2YoCDPF26pJpmwNisZtsdrsg1wAsDmkxVt9PU@yorWeJEnRbCeX5QKynY4@ghxKPlmivbblhDxHqyFhLwg3LCuwmEmP0ZrBiH2RBMed0C5Qn1sl54TpMkb8Lo/6BnWCBcPyjdAuMlrrJjY4OXHMk4QH1Ld4RfOITx1Gi4GukG@VykE@dEyIM1yf9ngs5HMFnxgVGsiw@T2sAuvSoNLdUEg5Bw2Xuc4Qp7alEMbV0A2oWWApWJRN0tCD5ZoZzggvZxnlfLjkUwL9jFRDygPLdRD3gC1JYKuB73plimGp2iGd1EEacXt2XN6FpmTcjAy5s4wurYaSid65v/4BdYHnZOyZQ/eG9@SYNjE8vZcbRYvR9KTlUI467xodCHbvhf4btU@AE3h2vCMByXU01YFIjubaZ8B/AQ%23BQN) has the code; place in the editors folder and run with BQN. The line with a `<;>` in editors/XCompose is either redundant or not functional, as there's also a `<semicolon>` line, and needs to be removed for it to work. Output is in editors/*.d.

Looks like you're offset by one for the keys just above the right hand (g,c,r,l) in XCompose. Could you confirm that inputrc has it right?

Some files might be tougher to handle, but this approach seems much easier to extend, and of course adding another key layout is trivial. I'll work on a version with command line arguments to control which files to generate, and then consider this solved?

**Comment by xelxebar** [comment]
Ha! That's cute. Much nicer solution!
Confirmed that `inputrc.dvorak` is correct. Good catch.

**Comment by mlochbaum** [comment]
All right, I've properly overengineered the script so there's a nice interface for this. Haven't found a good source for colemak or workman layouts, but all that's needed is a string that lists out the keys in the same order as the qwerty one.

**Pull request closed without merging**
